backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

display_url: https://oriolcastro.me

logo_url: https://oriolcastro.me/static/a21f9c9b7c7ca3cb1062a93c5a36fe4f/cdec6/me.webp

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "single-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
    # files:
    #   - file: "src/pages/about/index.md"
    #     label: "About"
    #     name: "about"
    #     fields:
    #     - {
    #           label: "Template Key",
    #           name: "templateKey",
    #           widget: "hidden",
    #           default: "portfolio-page",
    #         }
    #       - { label: "Title", name: "title", widget: "string" }
    #       - { label: "Featured Image", name: "thumbnail", widget: "image" }
    #       - { label: "Body", name: "body", widget: "markdown" }
